### PR TITLE
Switch the view helpers to the new Ruby hash notation

### PR DESCRIPTION
**Pull request by ayaman**

### CODE REVIEW

**Comment by mikeatlas** [comment]
Thanks. It's been a little while since I've actively touched Rails, and this gem never got fed through any linters.

**Comment by mikeatlas** [comment]
...or set up Travis for this gem either, there's not a lot of code here truthfully to test ... it's all just very strategic minimal glue and architectural choices for lightweight realtime/websockets. 

I know Rails has [ActionCable](https://github.com/rails/actioncable) now in Rails 4+? So I presume this gem will eventually fade into disuse as the need for additional Socket.io on Node.js for lightweight websocket handling gets more attention and support in Rails core...

**Comment by ayaman** [comment]
Well, actually ActionCable won't be part of the Rails core until Rails 5 as far as I know, and that still seems to be months away.

In the meantime, I'm working on an async version of the JS of this gem, will send you a PR with that as well when I'm done. I'd love to have your feedback on it.

**Comment by mikeatlas** [comment]
Async in what manner? Of course I'll have a look!

**Comment by ayaman** [comment]
I meant they'll be loaded in a non-blocking manner. Might have to make some additional changes on the way to make that transition smoother but will definitely keep you posted. Hopefully I'll have it done this week.

**Comment by mikeatlas** [comment]
Very curious where you're going RE: non-blocking? Are you witnessing demonstrable performance issues in the gem - initializers? As far as I know... in MRI Ruby, the GIL pretty much prevents you from doing things truly async anyways unless you go the route of multi-proc. But you can teach me something if you know how to do non-blocking I/O in Ruby on MRI.

**Comment by ayaman** [comment]
I think I didn't explain what I had in mind clearly enough. You're absolutely right regarding the GIL as far as I know but I'm only working on making the client-side JS load asynchronously so as not to block loading the rest of the front-end elements in case any of the external scripts couldn't be loaded for whatever reason. It should also have the benefits of making the loading a bit faster and keeping the front-end functionality independent of the socket connection (assuming it wasn't critical for the front-end of course).

**Comment by mikeatlas** [comment]
Oh, that totally makes for a good improvement. Yeah, I'm sure YSlow probably doesn't like the placement of the script in the top; personally I've forked and used this project in situations where it _had_ to load ahead of other scripts on the page [which expected a connection and events flowing over the socket].

**Pull request merged**
